/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import javax.swing.Timer;

/**
 *
 * @author mario
 */
public class Interfaz extends javax.swing.JFrame {
    String txt1 = "";
    String txt2 = "";
    int miliSeg = 0;
    int segundos = 0;
    int minutos = 0;
    int score1 = 0;
    int score2 = 0;
    int contadorTiempo = 0;
    boolean estado = true;
    /**
     * Creates new form Interfaz
     */
    public Interfaz(String str1, String str2) {
        initComponents();
        this.setLocationRelativeTo(null);
        txt1 = str1;
        txt2 = str2;
        Team1.setText(txt1);
        Team2.setText(txt2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelVS = new javax.swing.JLabel();
        Team1 = new javax.swing.JLabel();
        Team2 = new javax.swing.JLabel();
        jLabelScore2 = new javax.swing.JLabel();
        jLabelScore1 = new javax.swing.JLabel();
        jLabelTiempo = new javax.swing.JLabel();
        jLabelCrono = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jButttonSub1 = new javax.swing.JButton();
        jButtonAdd1 = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jButtonSub2 = new javax.swing.JButton();
        jButtonAdd2 = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, -1, -1));

        jLabelVS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vs2.png"))); // NOI18N
        getContentPane().add(jLabelVS, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        Team1.setFont(new java.awt.Font("Agency FB", 1, 100)); // NOI18N
        Team1.setForeground(new java.awt.Color(255, 255, 255));
        Team1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1.setText("TEAM1");
        getContentPane().add(Team1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 80, 610, -1));

        Team2.setFont(new java.awt.Font("Agency FB", 1, 100)); // NOI18N
        Team2.setForeground(new java.awt.Color(255, 255, 255));
        Team2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2.setText("TEAM2");
        getContentPane().add(Team2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 590, 110));

        jLabelScore2.setFont(new java.awt.Font("Agency FB", 1, 400)); // NOI18N
        jLabelScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScore2.setText("0");
        getContentPane().add(jLabelScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 460, 330));

        jLabelScore1.setFont(new java.awt.Font("Agency FB", 1, 400)); // NOI18N
        jLabelScore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScore1.setText("0");
        getContentPane().add(jLabelScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 440, 330));

        jLabelTiempo.setFont(new java.awt.Font("Arial", 1, 130)); // NOI18N
        jLabelTiempo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTiempo.setText("T   1");
        getContentPane().add(jLabelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabelCrono.setFont(new java.awt.Font("Agency FB", 1, 110)); // NOI18N
        jLabelCrono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCrono.setText("00:00");
        getContentPane().add(jLabelCrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, -1, -1));

        jLabelT.setFont(new java.awt.Font("Agency FB", 1, 110)); // NOI18N
        jLabelT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT.setText("TIEMPO:");
        getContentPane().add(jLabelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, -1, -1));

        jButttonSub1.setBackground(new java.awt.Color(0, 102, 0));
        jButttonSub1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButttonSub1.setText("<");
        jButttonSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButttonSub1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButttonSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jButtonAdd1.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAdd1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonAdd1.setText(">");
        jButtonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play.png"))); // NOI18N
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 600, -1, -1));

        jButtonSub2.setBackground(new java.awt.Color(0, 102, 0));
        jButtonSub2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonSub2.setText("<");
        jButtonSub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSub2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 450, -1, -1));

        jButtonAdd2.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAdd2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonAdd2.setText(">");
        jButtonAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 450, -1, -1));

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stp.png"))); // NOI18N
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 700, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pause.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 650, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CAMBIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));

        jButton5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButttonSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButttonSub1ActionPerformed
        // TODO add your handling code here:
        score1 --;
        if(score1 <= 0){
            jLabelScore1.setText("0");
            score1 = 0;
        }
        else{
            if(score1<10){
                jLabelScore1.setText(""+score1);
            }
            else{
                jLabelScore1.setText(""+score1);
            }
        }
    }//GEN-LAST:event_jButttonSub1ActionPerformed

    private void jButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd1ActionPerformed
        // TODO add your handling code here:
        score1 ++;
        if(score1<10){
            jLabelScore1.setText(""+score1);
        }
        else{
            jLabelScore1.setText(""+score1);
        }
    }//GEN-LAST:event_jButtonAdd1ActionPerformed

    private void jButtonSub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSub2ActionPerformed
        // TODO add your handling code here:
        score2 --;
        if(score2 <= 0){
            jLabelScore2.setText("0");
            score2 = 0;
        }
        else{
            if(score2<10){
                jLabelScore2.setText(""+score2);
            }
            else{
                jLabelScore2.setText(""+score2);
            }
        }
    }//GEN-LAST:event_jButtonSub2ActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        estado = true;
        Thread hilo = new Thread(){
            public void run(){
                for(;;){
                    if(estado){
                        try{
                            sleep(1000);
                            if(segundos >= 60){
                                segundos = 0;
                                minutos ++;
                            }
                            if(segundos < 10){
                                jLabelCrono.setText("0"+minutos+":0"+segundos);
                            }
                            else if(minutos < 10){
                                jLabelCrono.setText("0"+minutos+":"+segundos);
                            }
                            else{
                                jLabelCrono.setText(minutos+":"+segundos);
                            }
                            segundos ++;
                        }catch(Exception e){
                            System.out.println(e);
                        }
                    }else{
                        break;
                    }
                }
            }
        };
        hilo.start();
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        estado = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
        estado = false;
        miliSeg = 0;
        segundos = 0;
        minutos = 0;
        jLabelCrono.setText("00:00");
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd2ActionPerformed
        // TODO add your handling code here:
        score2 ++;
        if(score2<10){
            jLabelScore2.setText(""+score2);
        }
        else{
            jLabelScore2.setText(""+score2);
        }
    }//GEN-LAST:event_jButtonAdd2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Nombres name = new Nombres();
        name.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (contadorTiempo < 1){
            contadorTiempo = contadorTiempo + 1;
            jLabelTiempo.setText("T   2");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (contadorTiempo > 0){
            contadorTiempo = contadorTiempo - 1;
            jLabelTiempo.setText("T   1");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz("TEAM1","TEAM2").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Team1;
    private javax.swing.JLabel Team2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAdd1;
    private javax.swing.JButton jButtonAdd2;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonSub2;
    private javax.swing.JButton jButttonSub1;
    private javax.swing.JLabel jLabelCrono;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelScore1;
    private javax.swing.JLabel jLabelScore2;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelVS;
    // End of variables declaration//GEN-END:variables
}
